version: "3.8"
services:
  movies:
    image: thisismanjurocks/paytmmovies:latest
    ports:
      - 93:80
    deploy:
      replicas: 3
  train:
    image: thisismanjurocks/paytmtrain:latest
    ports:
      - 94:80
    deploy:
      replicas: 3
